services:
  - type: web
    name: clypso-api
    env: python
    buildCommand: pip install --no-cache-dir --upgrade -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ALLOWED_ORIGINS
        value: https://clypso.vercel.app,https://clypso.qzz.io
      - key: COOKIES_CONTENT
        sync: false
